version: '3.8'

services:
  # 1. The API Server
  backend:
    build: ./backend
    container_name: manhwa_backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672//
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - rabbitmq
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload

  # 2. The Worker
  worker:
    build: ./backend
    container_name: manhwa_worker
    env_file:
      - ./backend/.env
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672//
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - rabbitmq
    command: celery -A app.celery_app worker --loglevel=info --concurrency=2

  # 3. Result Backend
  redis:
    image: "redis:alpine"
    container_name: manhwa_redis
    ports:
      - "6379:6379"

  # 4. Task Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: manhwa_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
